// src/api/mockJobs.js
export const mockJobs = [
  {
    id: '1',
    title: 'Frontend-Entwickler/in',
    company: 'BFO AG',
    location: 'Bern',
    category: 'IT',
    region: 'BE',
    description: 'Entwicklung moderner Webapplikationen mit React. Mitarbeit in einem agilen Team.',
    homeOffice: true,
    language: 'Deutsch',
    workplace: 'Hybrid',
    url: 'https://jobs.bfo.ch/1',
    publishedAt: '2026-02-01T08:00:00Z'
  },
  {
    id: '2',
    title: 'Java-Entwickler/in',
    company: 'TechSolutions GmbH',
    location: 'Zürich',
    category: 'IT',
    region: 'ZH',
    description: 'Backend-Entwicklung mit Spring Boot. Aufbau von Microservices.',
    homeOffice: false,
    language: 'Englisch',
    workplace: 'Vor Ort',
    url: 'https://jobs.bfo.ch/2',
    publishedAt: '2026-01-28T10:30:00Z'
  },
  {
    id: '3',
    title: 'Marketing Manager/in',
    company: 'Swiss Marketing AG',
    location: 'Basel',
    category: 'Marketing',
    region: 'BS',
    description: 'Planung und Umsetzung von Kampagnen. Schwerpunkt Digital Marketing.',
    homeOffice: true,
    language: 'Deutsch',
    workplace: 'Remote',
    url: 'https://jobs.bfo.ch/3',
    publishedAt: '2026-02-05T09:15:00Z'
  },
  {
    id: '4',
    title: 'Projektleiter/in Bau',
    company: 'Bauplan AG',
    location: 'Sitten',
    category: 'Bau',
    region: 'VS',
    description: 'Leitung von Hochbauprojekten. Koordination von Subunternehmern.',
    homeOffice: false,
    language: 'Französisch',
    workplace: 'Vor Ort',
    url: 'https://jobs.bfo.ch/4',
    publishedAt: '2026-01-30T14:20:00Z'
  },
  {
    id: '5',
    title: 'HR-Assistent/in',
    company: 'PersonalPro',
    location: 'Luzern',
    category: 'Personalwesen',
    region: 'LU',
    description: 'Unterstützung im Recruiting und in der Personaladministration.',
    homeOffice: true,
    language: 'Deutsch',
    workplace: 'Hybrid',
    url: 'https://jobs.bfo.ch/5',
    publishedAt: '2026-02-03T11:00:00Z'
  },
  {
    id: '6',
    title: 'Sachbearbeiter/in Buchhaltung',
    company: 'Treuhand AG',
    location: 'Chur',
    category: 'Finanzen',
    region: 'GR',
    description: 'Debitoren- und Kreditorenbuchhaltung, Zahlungsverkehr.',
    homeOffice: false,
    language: 'Deutsch',
    workplace: 'Vor Ort',
    url: 'https://jobs.bfo.ch/6',
    publishedAt: '2026-02-02T13:45:00Z'
  }
];