/**
 * Mock job data for testing and development.
 *
 * Provides a static array of sample job listings that match the expected
 * API response format. Used as a fallback when the real API is unavailable
 * or when `useMock` mode is enabled.
 *
 * @module mockJobs
 */

/**
 * A collection of sample job objects for testing the Thin Client.
 *
 * Each job object conforms to the structure expected by the widget
 * components (`JobItem`, filter functions, etc.) and mirrors the
 * response format documented in `docs/api.md`.
 *
 * @constant {Array<Object>}
 * @property {string} id - Unique job identifier.
 * @property {string} title - Job title (German).
 * @property {string} company - Employer name.
 * @property {string} location - City of work.
 * @property {string} plz - Postal code.
 * @property {string} category - Professional category (e.g., "IT").
 * @property {string} canton - Canton or region code (e.g., "BE").
 * @property {string} description - Short job description (German).
 * @property {string} requirements - Required skills/experience.
 * @property {string} benefits - Benefits offered.
 * @property {boolean} homeOffice - Whether home office is possible.
 * @property {string} language - Main language required.
 * @property {string} workplace - Workplace type ("Remote", "Hybrid", "Vor Ort").
 * @property {string} url - Link to the full job posting.
 * @property {string} publishedAt - ISO 8601 publication date.
 * @property {string} contactEmail - Recruiting contact email.
 * @property {string} contactPhone - Recruiting contact phone number.
 *
 * @example
 * import { mockJobs } from './mockJobs.js';
 * console.log(mockJobs.length); // 46
 * console.log(mockJobs[0].title); // "Frontend-Entwickler/in"
 */
export const mockJobs = [
	{
		id: '1',
		title: 'Frontend-Entwickler/in',
		company: 'BFO AG',
		location: 'Bern',
		plz: '3000',
		category: 'IT',
		canton: 'BE',
		description: 'Entwicklung moderner Webapplikationen mit React.',
		requirements: 'Erfahrung mit JavaScript und CSS.',
		benefits: 'Flexible Arbeitszeiten, modernes Büro.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Hybrid',
		url: 'https://jobs.bfo.ch/1',
		publishedAt: '2026-02-01',
		contactEmail: 'recruiting@bfo.ch',
		contactPhone: '+41 31 123 45 67'
	},
	{
		id: '2',
		title: 'Java-Entwickler/in',
		company: 'TechSolutions GmbH',
		location: 'Zürich',
		plz: '8000',
		category: 'IT',
		canton: 'ZH',
		description: 'Backend-Entwicklung mit Spring Boot. Aufbau von Microservices.',
		requirements: 'Fundierte Java-Kenntnisse, Erfahrung mit Spring.',
		benefits: 'Weiterbildungsmöglichkeiten, zentrales Büro.',
		homeOffice: false,
		language: 'Englisch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/2',
		publishedAt: '2026-01-28T10:30:00Z',
		contactEmail: 'hr@techsolutions.ch'
	},
	{
		id: '3',
		title: 'Marketing Manager/in',
		company: 'Swiss Marketing AG',
		location: 'Basel',
		plz: '4000',
		category: 'Marketing',
		canton: 'BS',
		description: 'Planung und Umsetzung von Kampagnen. Schwerpunkt Digital Marketing.',
		requirements: 'Erfahrung in der Marketingbranche, Kreativität.',
		benefits: 'Homeoffice-Möglichkeit, dynamisches Team.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Remote',
		url: 'https://jobs.bfo.ch/3',
		publishedAt: '2026-02-05T09:15:00Z',
		contactPhone: '+41 61 234 56 78'
	},
	{
		id: '4',
		title: 'Projektleiter/in Bau',
		company: 'Bauplan AG',
		location: 'Sitten',
		plz: '1950',
		category: 'Bau',
		canton: 'VS',
		description: 'Leitung von Hochbauprojekten. Koordination von Subunternehmern.',
		requirements: 'Technisches Verständnis, Führungserfahrung.',
		benefits: 'Verantwortungsvolle Position, attraktive Anstellungsbedingungen.',
		homeOffice: false,
		language: 'Französisch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/4',
		publishedAt: '2026-01-30T14:20:00Z'
	},
	{
		id: '5',
		title: 'HR-Assistent/in',
		company: 'PersonalPro',
		location: 'Luzern',
		plz: '6000',
		category: 'Personalwesen',
		canton: 'LU',
		description: 'Unterstützung im Recruiting und in der Personaladministration.',
		requirements: 'Organisationstalent, diskrete Arbeitsweise.',
		benefits: 'Angenehmes Arbeitsklima, flexible Arbeitszeiten.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Hybrid',
		url: 'https://jobs.bfo.ch/5',
		publishedAt: '2026-02-03T11:00:00Z',
		contactEmail: 'personal@personalpro.ch',
		contactPhone: '+41 41 345 67 89'
	},
	{
		id: '6',
		title: 'Sachbearbeiter/in Buchhaltung',
		company: 'Treuhand AG',
		location: 'Chur',
		plz: '7000',
		category: 'Finanzen',
		canton: 'GR',
		description: 'Debitoren- und Kreditorenbuchhaltung, Zahlungsverkehr.',
		requirements: 'Kaufmännische Ausbildung, Zahlenaffinität.',
		benefits: 'Gute Sozialleistungen, moderner Arbeitsplatz.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/6',
		publishedAt: '2026-02-02T13:45:00Z'
	},
	{
		id: '7',
		title: 'DevOps Engineer',
		company: 'CloudNative AG',
		location: 'Zürich',
		plz: '8005',
		category: 'IT',
		canton: 'ZH',
		description: 'Aufbau und Betrieb von CI/CD-Pipelines, Container-Orchestrierung mit Kubernetes.',
		requirements: 'Erfahrung mit Docker, Kubernetes, Jenkins.',
		benefits: 'Moderne Technologien, flache Hierarchien.',
		homeOffice: true,
		language: 'Englisch',
		workplace: 'Remote',
		url: 'https://jobs.bfo.ch/7',
		publishedAt: '2026-02-07T08:00:00Z',
		contactEmail: 'jobs@cloudnative.ch'
	},
	{
		id: '8',
		title: 'Data Scientist',
		company: 'Insights AG',
		location: 'Lausanne',
		plz: '1003',
		category: 'IT',
		canton: 'VD',
		description: 'Analyse grosser Datenmengen, Entwicklung von Machine-Learning-Modellen.',
		requirements: 'Python, SQL, Erfahrung mit ML-Frameworks.',
		benefits: 'Innovatives Umfeld, internationale Projekte.',
		homeOffice: true,
		language: 'Französisch',
		workplace: 'Hybrid',
		url: 'https://jobs.bfo.ch/8',
		publishedAt: '2026-02-06T09:30:00Z'
	},
	{
		id: '9',
		title: 'Cloud Architect',
		company: 'NetSolutions GmbH',
		location: 'Zug',
		plz: '6300',
		category: 'IT',
		canton: 'ZG',
		description: 'Konzeption und Umsetzung von Cloud-Strategien (AWS, Azure).',
		requirements: 'Mehrjährige Erfahrung als Cloud-Architekt.',
		benefits: 'Attraktives Gehalt, Firmenwagen.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/9',
		publishedAt: '2026-02-04T11:15:00Z',
		contactPhone: '+41 41 456 78 90'
	},
	{
		id: '10',
		title: 'Elektroingenieur/in',
		company: 'Energie AG',
		location: 'Aarau',
		plz: '5000',
		category: 'Ingenieurwesen',
		canton: 'AG',
		description: 'Planung und Überwachung von Elektroprojekten im Energiesektor.',
		requirements: 'Studium Elektrotechnik, Kenntnisse in MSR-Technik.',
		benefits: 'Abwechslungsreiche Tätigkeit, ÖV-Abo.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Hybrid',
		url: 'https://jobs.bfo.ch/10',
		publishedAt: '2026-02-02T07:45:00Z'
	},
	{
		id: '11',
		title: 'Maschinenbauingenieur/in',
		company: 'SwissMechanic',
		location: 'Winterthur',
		plz: '8400',
		category: 'Ingenieurwesen',
		canton: 'ZH',
		description: 'Konstruktion und Entwicklung von Maschinenkomponenten mit CAD.',
		requirements: 'Erfahrung mit SolidWorks oder CATIA.',
		benefits: 'Eigenverantwortliches Arbeiten, Weiterbildung.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/11',
		publishedAt: '2026-01-29T16:20:00Z'
	},

	// Healthcare & Pharma
	{
		id: '12',
		title: 'Dipl. Pflegefachperson',
		company: 'Spital Bern AG',
		location: 'Bern',
		plz: '3010',
		category: 'Gesundheit',
		canton: 'BE',
		description: 'Pflege und Betreuung von Patienten auf der Chirurgiestation.',
		requirements: 'Diplom als Pflegefachperson, Belastbarkeit.',
		benefits: 'Dienstpläne frühzeitig, Personalrestaurant.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/12',
		publishedAt: '2026-02-08T12:00:00Z',
		contactEmail: 'personal@spitalbern.ch',
		contactPhone: '+41 31 567 89 01'
	},
	{
		id: '13',
		title: 'Apotheker/in',
		company: 'TopPharm',
		location: 'Basel',
		plz: '4051',
		category: 'Pharma',
		canton: 'BS',
		description: 'Beratung von Kunden, Rezepturherstellung, Teamführung.',
		requirements: 'Staatsexamen Pharmazie, Kommunikationsstärke.',
		benefits: 'Leistungsgerechte Vergütung, Fortbildungen.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/13',
		publishedAt: '2026-02-03T13:30:00Z'
	},
	{
		id: '14',
		title: 'Medizintechnik-Spezialist/in',
		company: 'MedTech AG',
		location: 'Luzern',
		plz: '6003',
		category: 'Pharma',
		canton: 'LU',
		description: 'Wartung und Inbetriebnahme von medizinischen Geräten.',
		requirements: 'Technische Ausbildung, Reisebereitschaft.',
		benefits: 'Dienstfahrzeug, spannende Einsätze.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/14',
		publishedAt: '2026-02-01T10:10:00Z'
	},

	// Sales & Retail
	{
		id: '15',
		title: 'Verkaufsberater/in',
		company: 'MediaMarkt',
		location: 'Spreitenbach',
		plz: '8957',
		category: 'Verkauf',
		canton: 'AG',
		description: 'Beratung von Kunden im Bereich Unterhaltungselektronik.',
		requirements: 'Verkaufstalent, technisches Interesse.',
		benefits: 'Mitarbeiterrabatte, leistungsorientierte Prämien.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/15',
		publishedAt: '2026-01-27T09:00:00Z'
	},
	{
		id: '16',
		title: 'Aussendienstmitarbeiter/in',
		company: 'Sanitär Huber',
		location: 'St. Gallen',
		plz: '9000',
		category: 'Verkauf',
		canton: 'SG',
		description: 'Akquisition von Neukunden, Betreuung bestehender Kunden im Sanitärbereich.',
		requirements: 'Verkaufserfahrung, Führerschein.',
		benefits: 'Erfolgsbeteiligung, flexibles Arbeiten.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Remote',
		url: 'https://jobs.bfo.ch/16',
		publishedAt: '2026-02-06T14:45:00Z',
		contactEmail: 'jobs@sanitaerhuber.ch'
	},
	{
		id: '17',
		title: 'Store Manager',
		company: 'Zara',
		location: 'Genf',
		plz: '1201',
		category: 'Verkauf',
		canton: 'GE',
		description: 'Leitung eines Modegeschäfts, Personalführung, Umsatzverantwortung.',
		requirements: 'Erfahrung im Einzelhandel, Führungsqualitäten.',
		benefits: 'Attraktiver Lohn, Karrierechancen.',
		homeOffice: false,
		language: 'Französisch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/17',
		publishedAt: '2026-01-31T08:30:00Z'
	},

	// Logistics & Transport
	{
		id: '18',
		title: 'Logistikleiter/in',
		company: 'LogistikSchweiz AG',
		location: 'Olten',
		plz: '4600',
		category: 'Logistik',
		canton: 'SO',
		description: 'Leitung des Lagers, Optimierung von Prozessen, Führung von 15 Mitarbeitern.',
		requirements: 'Weiterbildung im Logistikbereich, Führungserfahrung.',
		benefits: 'Herausfordernde Aufgabe, gute Anbindung.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/18',
		publishedAt: '2026-02-05T11:20:00Z',
		contactPhone: '+41 62 678 90 12'
	},
	{
		id: '19',
		title: 'Chauffeur/in CZV',
		company: 'Transport AG',
		location: 'Buchs SG',
		plz: '9470',
		category: 'Logistik',
		canton: 'SG',
		description: 'Internationale Fahrten, Zustellung von Waren.',
		requirements: 'Führerschein C, CZV-Ausweis.',
		benefits: 'Moderne Flotte, geregelte Arbeitszeiten.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/19',
		publishedAt: '2026-02-02T07:00:00Z'
	},
	{
		id: '20',
		title: 'Lagerist/in',
		company: 'Coop Logistik',
		location: 'Schafisheim',
		plz: '5503',
		category: 'Logistik',
		canton: 'AG',
		description: 'Kommissionierung, Verpackung und Versand von Lebensmitteln.',
		requirements: 'Lagererfahrung, körperliche Belastbarkeit.',
		benefits: 'Personalrabatte, Zulagen.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/20',
		publishedAt: '2026-02-07T15:10:00Z'
	},

	// Finance & Insurance
	{
		id: '21',
		title: 'Finanzberater/in',
		company: 'UBS AG',
		location: 'Zürich',
		plz: '8001',
		category: 'Finanzen',
		canton: 'ZH',
		description: 'Beratung von Privatkunden in Anlage- und Vorsorgefragen.',
		requirements: 'Erfahrung im Finanzbereich, Kundenorientierung.',
		benefits: 'Exzellente Sozialleistungen, Bonus.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Hybrid',
		url: 'https://jobs.bfo.ch/21',
		publishedAt: '2026-02-04T09:45:00Z',
		contactEmail: 'karriere@ubs.ch',
		contactPhone: '+41 44 789 01 23'
	},
	{
		id: '22',
		title: 'Versicherungsberater/in',
		company: 'AXA Winterthur',
		location: 'Winterthur',
		plz: '8400',
		category: 'Finanzen',
		canton: 'ZH',
		description: 'Betreuung von Privatkunden, Verkauf von Versicherungslösungen.',
		requirements: 'Kaufmännische Ausbildung, Kommunikationsgeschick.',
		benefits: 'Provisionen, Firmenwagen.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Hybrid',
		url: 'https://jobs.bfo.ch/22',
		publishedAt: '2026-01-28T13:00:00Z'
	},
	{
		id: '23',
		title: 'Treuhänder/in',
		company: 'TreuhandPartner',
		location: 'St. Gallen',
		plz: '9000',
		category: 'Finanzen',
		canton: 'SG',
		description: 'Führung von Jahresabschlüssen, Steuererklärungen für KMU.',
		requirements: 'Dipl. Treuhandexperte/in oder gleichwertig.',
		benefits: 'Flache Hierarchien, Homeoffice möglich.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Hybrid',
		url: 'https://jobs.bfo.ch/23',
		publishedAt: '2026-02-01T08:20:00Z'
	},

	// Hospitality & Gastronomy
	{
		id: '24',
		title: 'Koch / Köchin',
		company: 'Restaurant Kronenhalle',
		location: 'Zürich',
		plz: '8001',
		category: 'Gastronomie',
		canton: 'ZH',
		description: 'Zubereitung von traditionellen Schweizer Gerichten, Mise en Place.',
		requirements: 'Abgeschlossene Kochlehre, Kreativität.',
		benefits: 'Trinkgeld, Personalverpflegung.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/24',
		publishedAt: '2026-02-03T12:30:00Z',
		contactEmail: 'bewerbung@kronenhalle.ch'
	},
	{
		id: '25',
		title: 'Servicefachfrau/-mann',
		company: 'Hotel Schweizerhof',
		location: 'Bern',
		plz: '3011',
		category: 'Gastronomie',
		canton: 'BE',
		description: 'Servieren von Speisen und Getränken, Betreuung der Gäste.',
		requirements: 'Freundliches Auftreten, Belastbarkeit.',
		benefits: 'Flexible Arbeitszeiten, gute Stimmung im Team.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/25',
		publishedAt: '2026-02-06T18:00:00Z'
	},
	{
		id: '26',
		title: 'Hoteldirektor/in',
		company: 'Grand Hotel Locarno',
		location: 'Locarno',
		plz: '6600',
		category: 'Gastronomie',
		canton: 'TI',
		description: 'Gesamtverantwortung für ein 4-Sterne-Hotel, Personalführung, Budget.',
		requirements: 'Langjährige Hotellerieerfahrung, Führungsstärke.',
		benefits: 'Repräsentative Position, Dienstwohnung möglich.',
		homeOffice: false,
		language: 'Italienisch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/26',
		publishedAt: '2026-01-25T10:00:00Z',
		contactPhone: '+41 91 890 12 34'
	},

	// Education & Training
	{
		id: '27',
		title: 'Lehrperson Primarstufe',
		company: 'Schulgemeinde Uster',
		location: 'Uster',
		plz: '8610',
		category: 'Bildung',
		canton: 'ZH',
		description: 'Klassenlehrperson einer 4. Klasse, Unterricht in allen Fächern.',
		requirements: 'Lehrdiplom, Freude am Umgang mit Kindern.',
		benefits: 'Gute Anstellung, schönes Schulhaus.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/27',
		publishedAt: '2026-02-02T07:30:00Z'
	},
	{
		id: '28',
		title: 'Dozent/in für Informatik',
		company: 'Fachhochschule Nordwestschweiz',
		location: 'Windisch',
		plz: '5210',
		category: 'Bildung',
		canton: 'AG',
		description: 'Durchführung von Vorlesungen und Praktika im Bereich Softwareentwicklung.',
		requirements: 'Master/PhD, Lehrerfahrung.',
		benefits: 'Forschung möglich, flexible Arbeitszeit.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Hybrid',
		url: 'https://jobs.bfo.ch/28',
		publishedAt: '2026-02-05T14:15:00Z'
	},
	{
		id: '29',
		title: 'Kita-Fachperson',
		company: 'Kinderkrippe Regenbogen',
		location: 'Luzern',
		plz: '6004',
		category: 'Bildung',
		canton: 'LU',
		description: 'Betreuung und Förderung von Kleinkindern, Elternarbeit.',
		requirements: 'Ausbildung als FaBe Kinderbetreuung.',
		benefits: 'Kleines Team, Weiterbildungen.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/29',
		publishedAt: '2026-01-30T09:50:00Z'
	},

	// Administration & HR
	{
		id: '30',
		title: 'Sachbearbeiter/in Personal',
		company: 'Stadtverwaltung Bern',
		location: 'Bern',
		plz: '3000',
		category: 'Personalwesen',
		canton: 'BE',
		description: 'Bearbeitung von Personalakten, Erstellung von Arbeitszeugnissen.',
		requirements: 'Kaufmännische Ausbildung, Erfahrung in Personaladministration.',
		benefits: 'Öffentliche Anstellung, Gleitzeit.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Hybrid',
		url: 'https://jobs.bfo.ch/30',
		publishedAt: '2026-02-04T10:40:00Z'
	},
	{
		id: '31',
		title: 'Teamassistenz',
		company: 'Rechtsanwälte Meier & Partner',
		location: 'Zürich',
		plz: '8002',
		category: 'Verwaltung',
		canton: 'ZH',
		description: 'Unterstützung des Teams, Terminkoordination, Korrespondenz.',
		requirements: 'Kaufmännische Ausbildung, Diskretion.',
		benefits: 'Angenehmes Betriebsklima, zentral gelegen.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/31',
		publishedAt: '2026-02-01T12:00:00Z'
	},
	{
		id: '32',
		title: 'Empfangspersonal',
		company: 'Ärztezentrum Bellevue',
		location: 'Kreuzlingen',
		plz: '8280',
		category: 'Verwaltung',
		canton: 'TG',
		description: 'Patientenempfang, Telefondienst, Administration.',
		requirements: 'Freundliches Auftreten, Organisationstalent.',
		benefits: 'Teilzeit möglich, verkehrsgünstige Lage.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/32',
		publishedAt: '2026-02-07T13:10:00Z'
	},

	// Legal & Consulting
	{
		id: '33',
		title: 'Rechtsanwalt / Rechtsanwältin',
		company: 'Kellerhals Carrard',
		location: 'Bern',
		plz: '3011',
		category: 'Recht',
		canton: 'BE',
		description: 'Vertretung von Mandanten in Zivil- und Wirtschaftssachen.',
		requirements: 'Anwaltspatent, mehrjährige Berufserfahrung.',
		benefits: 'Anspruchsvolle Fälle, gutes Team.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Hybrid',
		url: 'https://jobs.bfo.ch/33',
		publishedAt: '2026-01-27T11:30:00Z'
	},
	{
		id: '34',
		title: 'Unternehmensberater/in',
		company: 'McKinsey & Company',
		location: 'Zürich',
		plz: '8001',
		category: 'Beratung',
		canton: 'ZH',
		description: 'Beratung von Top-Management in Strategiefragen, Analyse und Konzeption.',
		requirements: 'Hervorragender Uni-Abschluss, analytisches Denken.',
		benefits: 'Exzellente Karriereperspektiven, hohes Gehalt.',
		homeOffice: false,
		language: 'Englisch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/34',
		publishedAt: '2026-02-03T16:00:00Z'
	},

	// Media & Communication
	{
		id: '35',
		title: 'Redaktor/in',
		company: 'Tages-Anzeiger',
		location: 'Zürich',
		plz: '8021',
		category: 'Medien',
		canton: 'ZH',
		description: 'Recherche und Verfassen von Artikeln im Ressort Politik.',
		requirements: 'Journalistische Ausbildung, Schreibstärke.',
		benefits: 'Dynamische Redaktion, Homeoffice-Möglichkeit.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Hybrid',
		url: 'https://jobs.bfo.ch/35',
		publishedAt: '2026-02-02T08:15:00Z'
	},
	{
		id: '36',
		title: 'Social Media Manager/in',
		company: 'Wirz Werbung',
		location: 'Zürich',
		plz: '8005',
		category: 'Marketing',
		canton: 'ZH',
		description: 'Entwicklung und Umsetzung von Social-Media-Strategien für Kunden.',
		requirements: 'Erfahrung mit Social Media, Kreativität.',
		benefits: 'Junges Team, flache Hierarchien.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Remote',
		url: 'https://jobs.bfo.ch/36',
		publishedAt: '2026-01-29T14:30:00Z'
	},

	// Construction & Skilled Trades
	{
		id: '37',
		title: 'Polier / Vorarbeiter',
		company: 'Implenia AG',
		location: 'Dietikon',
		plz: '8953',
		category: 'Bau',
		canton: 'ZH',
		description: 'Führung einer Baustellengruppe, Termin- und Qualitätskontrolle.',
		requirements: 'Erfahrung als Polier, Führungsqualitäten.',
		benefits: 'Verantwortungsvolle Position, guter Lohn.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/37',
		publishedAt: '2026-02-05T07:00:00Z'
	},
	{
		id: '38',
		title: 'Elektroinstallateur/in EFZ',
		company: 'Elektro Schmid',
		location: 'Zug',
		plz: '6300',
		category: 'Bau',
		canton: 'ZG',
		description: 'Installation und Wartung von elektrischen Anlagen in Wohn- und Gewerbebauten.',
		requirements: 'Abgeschlossene Ausbildung, Selbstständigkeit.',
		benefits: 'Moderne Arbeitsmittel, Weiterbildung.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/38',
		publishedAt: '2026-02-01T09:20:00Z'
	},
	{
		id: '39',
		title: 'Maler/in',
		company: 'Malergeschäft Frei',
		location: 'Basel',
		plz: '4057',
		category: 'Bau',
		canton: 'BS',
		description: 'Innen- und Aussenanstriche, Tapezierarbeiten.',
		requirements: 'Berufserfahrung, sorgfältige Arbeitsweise.',
		benefits: 'Kleines Team, geregelte Arbeitszeiten.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/39',
		publishedAt: '2026-02-04T10:00:00Z'
	},

	// Misc additional roles for diversity
	{
		id: '40',
		title: 'Landwirt/in',
		company: 'Hofgemeinschaft',
		location: 'Affoltern im Emmental',
		plz: '3416',
		category: 'Landwirtschaft',
		canton: 'BE',
		description: 'Tierhaltung, Ackerbau, Hofmanagement.',
		requirements: 'Landwirtschaftliche Ausbildung, Interesse an biologischer Wirtschaftsweise.',
		benefits: 'Wohnen auf dem Hof, regionale Produkte.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/40',
		publishedAt: '2026-02-02T06:30:00Z'
	},
	{
		id: '41',
		title: 'Florist/in',
		company: 'Blumenhaus Schuler',
		location: 'Luzern',
		plz: '6003',
		category: 'Handwerk',
		canton: 'LU',
		description: 'Gestaltung von Sträussen und Gestecken, Kundenberatung.',
		requirements: 'Kreativität, abgeschlossene Ausbildung.',
		benefits: 'Familienbetrieb, Umsatzbeteiligung.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/41',
		publishedAt: '2026-02-03T15:45:00Z'
	},
	{
		id: '42',
		title: 'Hauswart/in',
		company: 'Immobilienverwaltung Meier',
		location: 'Winterthur',
		plz: '8400',
		category: 'Gebäudetechnik',
		canton: 'ZH',
		description: 'Reinigung und Unterhalt von Liegenschaften, kleinere Reparaturen.',
		requirements: 'Handwerkliches Geschick, Zuverlässigkeit.',
		benefits: 'Selbstständiges Arbeiten, Dienstwohnung möglich.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/42',
		publishedAt: '2026-01-26T08:00:00Z'
	},
	{
		id: '43',
		title: 'Tiermedizinische/r Praxisassistent/in',
		company: 'Kleintierklinik am See',
		location: 'Zürich',
		plz: '8008',
		category: 'Gesundheit',
		canton: 'ZH',
		description: 'Assistenz bei Behandlungen, Empfang, Administration.',
		requirements: 'Abgeschlossene Ausbildung als Tiermed. Praxisassistent/in.',
		benefits: 'Tiernahe Tätigkeit, angenehmes Team.',
		homeOffice: false,
		language: 'Deutsch',
		workplace: 'Vor Ort',
		url: 'https://jobs.bfo.ch/43',
		publishedAt: '2026-02-06T11:30:00Z'
	},
	{
		id: '44',
		title: 'Eventmanager/in',
		company: 'Messe Schweiz AG',
		location: 'Basel',
		plz: '4005',
		category: 'Marketing',
		canton: 'BS',
		description: 'Planung und Durchführung von Messen und Events.',
		requirements: 'Erfahrung im Eventmanagement, Organisationstalent.',
		benefits: 'Dynamisches Umfeld, Aufbau von Kontakten.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Hybrid',
		url: 'https://jobs.bfo.ch/44',
		publishedAt: '2026-01-31T13:00:00Z'
	},
	{
		id: '45',
		title: 'Umweltberater/in',
		company: 'Bundesamt für Umwelt',
		location: 'Ittigen',
		plz: '3063',
		category: 'Beratung',
		canton: 'BE',
		description: 'Beratung von Gemeinden und Unternehmen in Umweltfragen.',
		requirements: 'Hochschulabschluss im Umweltbereich.',
		benefits: 'Öffentliche Anstellung, sinnstiftende Tätigkeit.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Hybrid',
		url: 'https://jobs.bfo.ch/45',
		publishedAt: '2026-02-07T09:00:00Z'
	},
	{
		id: '46',
		title: 'IT-Supportspezialist/in',
		company: 'Swisscom',
		location: 'Bern',
		plz: '3050',
		category: 'IT',
		canton: 'BE',
		description: 'First- und Second-Level-Support für interne Mitarbeiter.',
		requirements: 'IT-Grundausbildung, Kommunikationsfähigkeit.',
		benefits: 'Gute Sozialleistungen, Vergünstigungen.',
		homeOffice: true,
		language: 'Deutsch',
		workplace: 'Hybrid',
		url: 'https://jobs.bfo.ch/46',
		publishedAt: '2026-02-05T08:30:00Z'
	}
];